---
fail_fast: false

exclude: |
  (?x)^(
    build/ |
    dist/ |
  )$

repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  # Protect secrets using Gitleaks
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  # Spell check
  - repo: https://github.com/crate-ci/typos
    rev: v1.22.9
    hooks:
      - id: typos
  # Supported base hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  # Hadolint Dockerfile linter
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint
        args: [--config, ./.linters/.hadolint.yaml]
  # YAML linter
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--config-file, ./.linters/.yaml-lint.yml]
  # SQL linter
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.7
    hooks:
      - id: sqlfluff-lint
        args: [--config, ./.linters/.sqlfluff]
  # Markdown lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: [-c, ./.linters/.markdownlint.yml]
        types: [file]
        files: .(md|qmd)$
  # Add trailing commas to calls and literals.
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
  # PEP 8 style guide, error and complexity checks
  # Replaces Black, Flake8, isort, pydocstyle, pyupgrade, bandit, and autoflake
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.0
    hooks:
      # Run the Ruff linter.
      - id: ruff
        args: [--config=./.linters/.ruff.toml, --fix, --exit-non-zero-on-fix]
      # Run the Ruff formatter.
      - id: ruff-format
        args: [--config=./.linters/.ruff.toml]
  # Mypy static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
    -   id: mypy
  # Local hooks only
  - repo: local
    hooks:
      # Run unit tests using pytest. May not be a desirable thing to include
      # in pre-commit, but the option is there.
      - id: pytest
        name: pytest
        language: python
        additional_dependencies: [pytest, pytest-cov, coverage, fastapi, httpx]
        entry: pytest -sv
        require_serial: true
        pass_filenames: false
        files: \.py$
