---
repos:
  # Protect secrets using Gitleaks
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.2
    hooks:
      - id: gitleaks
  # Supported base hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  # YAML linter
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint
        args: [--config-file, ./.github/linters/.yaml-lint.yml]
  # SQL linter
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.0.0a3
    hooks:
      - id: sqlfluff-lint
        args: [--config, ./.github/linters/.sqlfluff]
  # Markdown lint
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        args: [-t, ~line_length]
  # Add trailing commas to calls and literals.
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  # Type checks
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive, --ignore-missing-imports]
  # Format Python docstrings
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.3
    hooks:
      - id: pydocstringformatter
  # Opinionated code styling
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  # PEP 8 style guide, error and complexity checks
  # Replaces Flake8, isort, pydocstyle, yesqa, eradicate, pyupgrade, and autoflake
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.224
    hooks:
      - id: ruff
        args: [--config=./.github/linters/ruff.toml, --fix]
  # Security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [--skip=B101]
