---
services:
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      [
        "python",
        "-m",
        "uvicorn",
        "boilerplate.api:app",
        "--reload",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]
    volumes:
      - .:/usr/local/app
    depends_on:
      - caddy
    restart: always

volumes:
  caddy_data:
  caddy_config:
